Template defined in header should not be on library boundary since it will be redefined in each compilation. Resolve "error C2491: 'caffe2::opt::fuseActivation': definition of dllimport function not allowed".